# Generated by Django 5.0.1 on 2024-02-27 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_BooksManagement', '0001_initial'),
        ('App_ShopManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='holderName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_BooksManagement.book'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_ShopManagement.shoppingcart'),
        ),
    ]
